name = "r2-static-worker"
account_id = "ab2449bd777040e47f49f01ef6021e83"
workers_dev = true
compatibility_date = "2022-07-08"
main = "src/index.ts"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "koding-static"
preview_bucket_name = "koding-static-preview"

[site]
bucket = "./view"